package raw.java.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JTextField;

/**
 * Listener for the reset button.
 * 
 * @author andreas
 */
public class AL_ResetButton implements ActionListener {
	private MapPanel mPanel;
	private JTextField textFieldSize; // Text field for map size input
	private JTextField textFieldSeed; // Text field for seed input

	/**
	 * Constructor. Is passed a reference to a MapPanel.
	 * 
	 * @param mp
	 *            the MapPanel the JButton will be linked to.
	 */
	public AL_ResetButton(MapPanel mp, JTextField sz, JTextField ss) {
		mPanel = mp;
		textFieldSize = sz;
		textFieldSeed = ss;
	}

	/**
	 * Called by the JButton button. Resets the simulation with new seed and new
	 * size.
	 * 
	 * @param arg0
	 *            an event generated by the button this listener is listening
	 *            on.
	 */
	@Override
	public void actionPerformed(ActionEvent arg0) {
		mPanel.getMap().simulationResetStop();
		// mPanel.getMap().setMapSize(mPanel.getDefaultSize());

		/*
		 * Attempts to retrieve a size from the size text field. If that fails
		 * it uses a default size as configured here.
		 */
		Integer size;
		size = Integer.parseInt(textFieldSize.getText());
		if (size != null) {
			mPanel.getMap().setMapSize(size);
			System.err.println("size: " + size);
		} else {
			mPanel.getMap().setMapSize(25);
		}

		/*
		 * Attempts to retrieve a seed from the seed text field. If that fails
		 * it uses a default seed as configured here.
		 */
		Integer seed;
		seed = Integer.parseInt(textFieldSeed.getText());
		if (seed != null) {
			mPanel.getMap().setSeed(seed);
			System.err.println("seed: " + seed);
		} else {
			mPanel.getMap().setSeed(0);
		}
		
		mPanel.getMap().simulationReset();
		mPanel.resetMapSize();
		mPanel.repaint();
	}
}